### ISSUE TITLE
Text not tweening?

### ISSUE THREAD

**Issue by Caligari** [SergioRibera/bevy_splash_screen#2]
I've been fiddling around with this cool crate, but I wasn't seeing Text being faded in and out.

Looking at lib.rs, where you are doing the build for the Plugin, surely you need to create a system for

`component_animator_system::<Text>.run_if(in_state(self.state.clone())),`

in addition to the one for BackgroundColor (which makes the images fade)?

That seems to fix my problems, at least.

**Comment by SergioRibera** [comment]
In fact the text works correctly, you can look at the implementations I made for this plugin [here](https://github.com/SergioRibera/bevy_splash_screen/blob/main/src/lens.rs), I created some lens specifically for the text and for the images, it should work correctly, but please as the readme says don't forget to use the patch for [bevy tweening](https://github.com/SergioRibera/bevy_splash_screen#usage), are you having any problem with the plugin? Or is it a suggestion, in any case I'm open to review any PR you want to do or if you don't think you can do it tell me a little more and I can integrate it in a next release 😄

**Comment by Caligari** [comment]
Ah, all good!
I was using a local clone of the tweening and I didn't have the features set correctly.
Thanks for your help! And for the crate!
