### ISSUE TITLE
Compiling examples on linux

### ISSUE THREAD

**Issue by LeCalicot** [SergioRibera/bevy_splash_screen#7]
I have cloned the repo locally on my linux computer and I could not compile the examples, while building the dependencies, winit complained that it couldn't compile winit for my platform.

Following https://github.com/djeedai/bevy_hanabi/issues/170, I have changed `default-features = true` for bevy in the cargo.toml and then it works.

**Comment by SergioRibera** [comment]
> I have cloned the repo locally on my linux computer and I could not compile the examples, while building the dependencies, winit complained that it couldn't compile winit for my platform.
> 
> Following [djeedai/bevy_hanabi#170](https://github.com/djeedai/bevy_hanabi/issues/170), I have changed `default-features = true` for bevy in the cargo.toml and then it works.

Thank you very much for telling me about this error, I didn't know about it, do you dare to do a PR or do you prefer me to do a commit fixing the problem?

**Comment by LeCalicot** [comment]
There might be side effects that I'm not aware of, so better if you do it.

**Comment by SergioRibera** [comment]
> There might be side effects that I'm not aware of, so better if you do it.

Okay, no problem, I'll check it out right away 😄

**Comment by CrawKatt** [comment]
I'll take care of it

**Comment by SergioRibera** [comment]
Fixed with PR #9

**Comment by LeCalicot** [comment]
I confirm, it works.
